# ===== Server =====
spring.application.name=SocialConnection
server.port=8083

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/social_connection_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Redis =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

# ===== Kafka =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=social-connection-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===== Eureka =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===== JWT =====
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationMustBeAtLeast256Bits
